services:
  - type: web
    name: essay-evaluator
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        fromService:
          type: secret
          name: gemini-api-key
      # Don’t force PORT, let platform inject it
    plan: free
